<h2>Promise.resolve(value) и Promise.reject(error)</h2>

<ul class="list-point">
	<li><bg-methods>Promise.resolve</bg-methods><bg-arguments>(value)</bg-arguments> - создаёт успешно выполнившийся промис с результатом value</li>
	<li>Promise.resolve используют, когда хотят построить асинхронную цепочку, и начальный результат уже есть</li>
</ul>

<pre><code class="js">
// аналогичен конструкции
new Promise((resolve) => resolve(value))
Promise.resolve(window.location) // начать с этого значения
	.then(httpGet) // вызвать для него httpGet
	.then(alert) // и вывести результат
</code></pre>

<ul class="list-point">
	<li><bg-methods>Promise.reject</bg-methods><bg-arguments>(error)</bg-arguments> - создаёт уже выполнившийся промис с ошибкой error</li>
	<li>Метод Promise.reject используется очень редко, т.к. ошибка возникает обычно не в начале цепочки, а в процессе её выполнения</li>
</ul>

<pre><code class="js">
Promise.reject(new Error("..."))
	.catch(alert) // Error: ...
</code></pre>
